# Generated by Django 4.2.21 on 2025-06-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_name_subject_title_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
